<template>
  <svg
    width="380"
    height="315"
    viewBox="0 0 380 315"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    class="pointer-events-none absolute left-1/2 top-0 w-full -translate-x-1/2"
  >
    <g filter="url(#filter0_f_120_7473)">
      <circle
        cx="34"
        cy="52"
        r="114"
        fill="#6925E7"
      />
    </g>
    <g filter="url(#filter1_f_120_7473)">
      <circle
        cx="332"
        cy="24"
        r="102"
        fill="#8A4BFF"
      />
    </g>
    <g filter="url(#filter2_f_120_7473)">
      <circle
        cx="191"
        cy="53"
        r="102"
        fill="#802FE3"
      />
    </g>
    <defs>
      <filter
        id="filter0_f_120_7473"
        x="-192"
        y="-174"
        width="452"
        height="452"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood
          flood-opacity="0"
          result="BackgroundImageFix"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="56"
          result="effect1_foregroundBlur_120_7473"
        />
      </filter>
      <filter
        id="filter1_f_120_7473"
        x="70"
        y="-238"
        width="524"
        height="524"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood
          flood-opacity="0"
          result="BackgroundImageFix"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="80"
          result="effect1_foregroundBlur_120_7473"
        />
      </filter>
      <filter
        id="filter2_f_120_7473"
        x="-71"
        y="-209"
        width="524"
        height="524"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood
          flood-opacity="0"
          result="BackgroundImageFix"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="80"
          result="effect1_foregroundBlur_120_7473"
        />
      </filter>
    </defs>
  </svg>
</template>
